language: go

go:
  - 1.7

sudo: false

before_install:
  # Redo the travis setup but with the christiangalsterer/httpbeat path. This is needed so the package path is correct
  - mkdir -p $HOME/gopath/src/github.com/christiangalsterer/httpbeat
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/christiangalsterer/httpbeat/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/christiangalsterer/httpbeat
  - cd $HOME/gopath/src/github.com/christiangalsterer/httpbeat

install:
  - make

script:
  - make testsuite

after_success:
  # Copy profile.cov to coverage.txt because codecov.io requires this file
  - cp build/coverage/full.cov full.txt
  - bash <(curl -s https://codecov.io/bash)
